#if UNITY_EDITOR
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
using Core.Environment;
using TMPro;
using System.Collections.Generic;

/// <summary>
/// Ajusta y sincroniza todos los HUDs 3D de los interactuables en la escena:
/// 1. Asegura que el GameObject del HUD ("HUD_Texto") sea hijo exacto de cada objeto interactuable.
/// 2. Aplica las proporciones unificadas exactas (sizeDelta 8x2.5, fontSize 4, color dorado, centrado).
/// 3. Elimina huérfanos/HUDs duplicados antiguos ("HUD_AutoGenerated", etc.) que ya no se utilicen.
/// 4. Asigna la referencia en InteractableHUD y UniversalQuestInteractable.
///
/// Menu: Lobo Game -> Normalizar y Unificar HUDs en Escena
/// </summary>
public static class FixHUDHierarchyAndProportions
{
    [MenuItem("Lobo Game/Normalizar y Unificar HUDs en Escena")]
    public static void NormalizarHUDs()
    {
        int ajustados = 0;
        int borrados = 0;
        var interactables = Object.FindObjectsByType<UniversalQuestInteractable>(FindObjectsSortMode.None);

        foreach (var uqi in interactables)
        {
            // 1. Obtener o añadir el componente InteractableHUD
            var hudComp = uqi.GetComponent<InteractableHUD>();
            if (hudComp == null)
            {
                hudComp = Undo.AddComponent<InteractableHUD>(uqi.gameObject);
            }

            // 2. Buscar todos los hijos que sean HUDs previos
            List<Transform> viejosHijos = new List<Transform>();
            Transform hijoValido = null;

            foreach (Transform t in uqi.transform)
            {
                if (t.name.StartsWith("HUD_Texto") || t.name.StartsWith("HUD_AutoGenerated") || t.GetComponent<TextMeshPro>() != null)
                {
                    if (hijoValido == null)
                    {
                        hijoValido = t;
                    }
                    else
                    {
                        viejosHijos.Add(t);
                    }
                }
            }

            // 3. Crear o renombrar el HUD válido
            GameObject hudObj = null;
            if (hijoValido != null)
            {
                hudObj = hijoValido.gameObject;
                hudObj.name = "HUD_Texto";
            }
            else
            {
                hudObj = new GameObject("HUD_Texto", typeof(TextMeshPro));
                hudObj.transform.SetParent(uqi.transform, false);
                hudObj.transform.localPosition = new Vector3(0f, 2.0f, 0f);
                Undo.RegisterCreatedObjectUndo(hudObj, "Crear HUD_Texto");
            }

            // 4. Borrar HUDs duplicados o antiguos sobrantes en la jerarquía de este objeto
            foreach (var viejo in viejosHijos)
            {
                if (viejo != null && viejo.gameObject != hudObj)
                {
                    Undo.DestroyObjectImmediate(viejo.gameObject);
                    borrados++;
                }
            }

            // 5. Unificar proporciones del TextMeshPro 3D
            var tmp = hudObj.GetComponent<TextMeshPro>();
            if (tmp != null)
            {
                Undo.RecordObject(tmp, "Unificar Proporciones HUD");
                tmp.rectTransform.sizeDelta = new Vector2(8f, 2.5f);
                tmp.fontSize = 4f;
                tmp.alignment = TextAlignmentOptions.Center;
                tmp.textWrappingMode = TextWrappingModes.Normal;
                tmp.color = new Color(1f, 0.9f, 0.2f, 1f); // Dorado/Amarillo
                if (string.IsNullOrEmpty(tmp.text))
                {
                    tmp.text = !string.IsNullOrEmpty(uqi.customUIMessage) ? uqi.customUIMessage : "Pulsa [E] para interactuar";
                }
            }

            // 6. Asignar referencias cruzadas limpias
            Undo.RecordObject(hudComp, "Asignar Referencias HUD");
            hudComp.hudObject = hudObj;
            hudComp.hudText = tmp;
            hudComp.mensajePorDefecto = !string.IsNullOrEmpty(uqi.customUIMessage) ? uqi.customUIMessage : "Pulsa [E] para interactuar";

            Undo.RecordObject(uqi, "Enlazar InteractableHUD");
            uqi.interactableHUD = hudComp;
            uqi.hudObject = hudObj;
            uqi.hudText = tmp;

            hudObj.SetActive(false);
            EditorUtility.SetDirty(uqi.gameObject);
            ajustados++;
        }

        EditorSceneManager.MarkSceneDirty(UnityEngine.SceneManagement.SceneManager.GetActiveScene());

        EditorUtility.DisplayDialog(
            "Limpieza y Unificación Completada",
            $"Se han ajustado {ajustados} HUDs principales.\n" +
            $"Se han eliminado {borrados} HUDs antiguos o duplicados de la jerarquía.\n\n" +
            "Recuerda guardar la escena (Ctrl+S).",
            "OK");

        Debug.Log($"[FixHUDHierarchyAndProportions] {ajustados} HUDs ajustados. {borrados} HUDs duplicados eliminados.");
    }
}
#endif
