using UnityEngine;
using TMPro;

namespace Core.Environment
{
    /// <summary>
    /// Componente ligero que gestiona el HUD 3D flotante de un interactuable.
    /// Separa la responsabilidad del billboard, texto y visibilidad del HUD
    /// de la logica principal de UniversalQuestInteractable.
    /// </summary>
    public class InteractableHUD : MonoBehaviour
    {
        [Header("HUD Flotante 3D")]
        [Tooltip("GameObject con el TextMeshPro 3D. Se crea automaticamente si es null.")]
        public GameObject hudObject;
        public TextMeshPro hudText;

        [Tooltip("Mensaje por defecto cuando el jugador esta en zona.")]
        public string mensajePorDefecto = "Pulsa [E] para interactuar";

        private Camera _cachedCam;

        private void Awake()
        {
            if (_cachedCam == null) _cachedCam = Camera.main;
        }

        private void Update()
        {
            if (hudObject == null || !hudObject.activeSelf) return;

            // Billboard: el texto siempre mira hacia la camara
            if (_cachedCam == null) _cachedCam = Camera.main;
            if (_cachedCam != null)
            {
                Vector3 dir = hudObject.transform.position - _cachedCam.transform.position;
                if (dir.sqrMagnitude > 0.001f)
                    hudObject.transform.rotation = Quaternion.LookRotation(dir);
            }
        }

        /// <summary>Crea el HUD automáticamente si no existe, y asegura la configuración base sin sobreescribir escala ni datos asignados.</summary>
        public void EnsureCreated(float alturaLocal = 2.0f)
        {
            if (hudObject == null)
            {
                // Buscar si existe un hijo llamado HUD_Texto o HUD_AutoGenerated
                Transform hijoHud = transform.Find("HUD_Texto") ?? transform.Find("HUD_AutoGenerated");
                if (hijoHud != null)
                {
                    hudObject = hijoHud.gameObject;
                    hudText = hijoHud.GetComponent<TextMeshPro>();
                }
                else
                {
                    var go = new GameObject("HUD_Texto", typeof(TextMeshPro));
                    go.transform.SetParent(transform, false);
                    go.transform.localPosition = new Vector3(0f, alturaLocal, 0f);

                    hudText = go.GetComponent<TextMeshPro>();
                    hudObject = go;
                }
            }

            if (hudText == null && hudObject != null)
            {
                hudText = hudObject.GetComponent<TextMeshPro>();
            }

            if (hudText != null)
            {
                // Solo establecer proporciones por defecto si es recién creado y no tenía configuración previa
                if (hudText.fontSize == 0)
                {
                    hudText.rectTransform.sizeDelta = new Vector2(8f, 2.5f);
                    hudText.fontSize = 4f;
                    hudText.alignment = TextAlignmentOptions.Center;
                    hudText.textWrappingMode = TextWrappingModes.Normal;
                    hudText.color = new Color(1f, 0.9f, 0.2f, 1f); // Dorado
                }
            }

            if (!string.IsNullOrEmpty(mensajePorDefecto) && hudText != null && string.IsNullOrEmpty(hudText.text))
                hudText.text = mensajePorDefecto;

            if (hudObject != null && !hudObject.activeSelf)
                hudObject.SetActive(false);
        }

        /// <summary>Muestra u oculta el HUD.</summary>
        public void SetVisible(bool visible)
        {
            if (hudObject != null) hudObject.SetActive(visible);
        }

        /// <summary>Cambia el texto del HUD.</summary>
        public void SetTexto(string texto)
        {
            if (hudText != null) hudText.text = texto;
        }

        /// <summary>True si el HUD esta visible.</summary>
        public bool IsVisible => hudObject != null && hudObject.activeSelf;
    }
}
